id = "pathy"
name = "Pathy"
version = "0.1.0"
schema_version = 1
description = "Sidecar LSP server for Python path completions."
authors = ["Your Name <you@example.com>"]
repository = "https://github.com/gokulp01/pathy"
capabilities = [
  { kind = "process:exec", command = "*", args = ["**"] },
  { kind = "download_file", host = "github.com", path = ["**"] }
]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.pathy]
language = "Python"
languages = []

[language_servers.pathy.language_ids]
Python = "python"
